### PR TITLE
Automated update of JSON files from gamedata (2.47.2.76003)

### PR DESCRIPTION
**Pull request by MGatner**
Latest patch data and a few bug fixes from upstream HDP.

@stuaroo Take a look when you have a chance, I'll merge tonight if I haven't heard anything.

### CODE REVIEW

**Comment by stuaroo** [comment]
@MGatner Looks like a lot of the prior issues have been cleaned up, well done!  I did notice a few minor things, but overall it's looking great:

* `0` key under abilities: D.Va/Pilot Mode, Abathur/Symbiote both replaced with `0`
* Gul'dan has two Life Tap traits
* Chen has W1 and W3 with no W2
* Samuro/Image Transmission has R as a hotkey instead of D
* Thrall trait has a cooldown

**Comment by MGatner** [comment]
Good finds! I fixed all those, and they were indeed on my end, except for Chen. W2 is actually his Earth elemental - the numbering is unfortunate but it takes abilities in order and his keg smash alt ability falls after the elementals.

If all looks good feel free to merge and I can create a release, and we should be back on schedule for prompt repo updates after patches.

**Comment by stuaroo** [comment]
@MGatner Spotted a couple more issues I missed the first time:

* Traits for Li Li and Stitches both have cooldowns
* Malthael/On a Pale Horse has `abilityLinks` to `Alexstrasza|Z1`; I wonder if the link code is  attempting to find the first Mount it can, because I believe it grabbed `Auriel|Z1` earlier

Also, I just noticed HDP updated to 4.2.2 to fix the Hanzo and Tassadar bugs, so if we update to the newest version and squash these few bugs I think we will be good to merge!

**Comment by MGatner** [comment]
Lots of incidental changes with v4.2.2 but I think we hit the important things. I have to go to bed but I'll give it another look-over tomorrow unless you get a chance to @stuaroo

**Comment by stuaroo** [comment]
@MGatner One last thing: Vikings have their trait `Viking Hoard` listed twice.

Other than that, the only remaining thing is the Malthael/Pale Horse abilityLinks, but I believe even that was off prior to the HDP upgrade (I think it pointed to `stormhero` or something similar).  I don't see that as a high priority issue, and I would be good with merging at this point.

**Comment by MGatner** [comment]
I updated those by hand but fixed the ability name on the generic `mount` ability (which should correct "On a Pale Horse" for the next run) and opened the following issue for TLV trait duplication: https://github.com/koliva8245/HeroesDataParser/issues/54

Based off your previous comment I'm going to proceed with merge - thanks for the thorough review!

**Pull request merged**
