### PR TITLE
heroes-convert version, take 2 (2.48.2.76781)

### PR DESCRIPTION
**Pull request by MGatner**
Second attempt on the new scripted conversion method. Unfortunately **heroes-data** is missing `2.48.0.76389` and the format is different from what we have in **raw/** so I had to stick with `2.48.2.76781` for now. I tweaked the ordering so hopefully it is more consistent with the current repo version. I do see a handful of things moving around but it looks like a lot of it is heroics moving into correct order (e.g. R2 after R1).

I'm leaving Chen & TLV in place for reference but whenever we are ready to merge I will reset them to their current repo versions since I don't anticipate having time to dig into them soon.

### CODE REVIEW

**Comment by stuaroo** [comment]
@MGatner  Some of these may be HDP issues, I haven't checked that yet as I wanted to send you feedback sooner rather than later.  I'll update this or post another reply if I figure out any of these are issues with the raw output.

**General Issues**

* Cooldowns: some have been increased by very large amounts; seem to be prefixed by 4 for some reason
	* Cassia: Lightning Fury cooldown increased from 4 to 44
	* Kael'thas: Verdant Spheres cooldown increased from 6 to 46
	* Samuro: Critical Strike cooldown increased from 10 to 410
	* Zagara: Envenomed Spines cooldown increased from 30 to 430
* Cooldowns: decimal cooldowns seem to be losing their decimal
	* Auriel: Bestow Hope cooldown changed from 1.5 to 15
	* Gul'dan: Fel Flame cooldown increased from 1.5 to 15
	* Uther: Flash of Light cooldown increased from 1.5 to 15
* Cooldowns: some have just been deleted altogether
	* Johanna: Indestructible cooldown removed
	* Lucio: Reverse Amp cooldown removed
	* Diablo: Black Soulstone cooldown removed (I actually didn't know it had a cooldown, was that correct before?)
	* Gall: Runic Blast cooldown removed
	* Nazeebo: Gargantuan Stomp cooldown removed
	* Uther: Devotion cooldown removed
* Activatable traits (i.e. hotkey D) have had their hotkey removed:
	* e.g. Arthas, Azmodan, Blaze, Cho, etc.
* Mana per second abilities have 'second' as manaCost and have `manaPerSecond` boolean removed
	* e.g. Arthas/Frozen Tempest, Chromie/Slowing Sands, Lt. Morales/Healing Beam, etc.
* Hotkeys of 1 changed from string to int; with most hotkeys being strings, I think we might want to standarize that
	* e.g. Gazlowe/Focus Turrents, Jaina/Ice Block, Kel'Thuzad/Glacial Spike, etc.
* Some talents have empty `abilityLinks` lists
	* Orphea/Invasive Miasma, Varian/Glory to the Alliance, Yrel/Divine Steed, Garrosh/Inner Rage
* Some secondary units are duplicating basic abilities that are not available to them
	* Ragnaros: duplicate/incorrect basic abilities added under `RagnarosBigRag`
	* Tychus: duplicate/incorrect basic abilities added under `TychusOdinNoHealth`
	* Uther: duplicate/incorrect Holy Light added under `UtherEternalDevotion`
* Some secondary units have been added for Heroes with abilities granted by trait quests
	* `JainaTraitFrostbite` added for Ice Block, `KelThuzadMasterOfTheColdDark` added for Glacial Spike

**More Specific/One-off Issues**

* Alexstrasza had Life-Binder added under Dragonqueen 
* Anub'arak release patch has a trailing space (it's on [Intervene](https://github.com/tattersoftware/heroes-convert/blob/develop/src/Intervene.php) too, so I think you'll just need to fix it there)
* Garrosh: Oppressor had a trailing space in its name added
* Dehaka: Trait-related talents have had their `abilityId` and `abilityLinks` dropped
* Malthael: On a Pale Horse `abilityLinks` changed to Greymane|Z1
	* This one always likes to have issues with abilityLinks
* Nazeebo: `type` has changed under `WitchDoctorGargantuan` abilities from `subunit` to `heroic`

**Comment by stuaroo** [comment]
@MGatner Updated the list from yesterday, I think the large cooldown increases may be related to color tags used in the gamestrings file and most of the deleted cooldowns should be deleted (with the exception of Gargantuan Stomp)

**Comment by MGatner** [comment]
Ah thanks, this is awesome! You're so thorough @stuaroo :) I'll get to this soon

**Comment by MGatner** [comment]
@stuaroo I think this is ready! I got through the rest of the specifics you found, and did a little cleanup. A few issues were upstream so I opened issues on them (https://github.com/HeroesToolChest/HeroesDataParser/issues) and then updated manually (like Dehaka trait). Chen wasn't changed nearly as much as I thought, and I did some work on TLV but I think they might actually be arranged better than before - see what you think.

**Comment by stuaroo** [comment]
@MGatner Nice work!  I think you fixed about everything from the earlier list.  Found a few additional things:

* Some abilities with type of `subunit` have been changed to `basic`
	* AbathurSymbiote, DVaPilot, LeoricUndyingTrait, ChenStormEarthFire, RagnarosBigRag, etc.
	* Not sure how important this is, but thought I'd mention it
* Some non-activateable traits now have a hotkey D
	* Falstad/Tailwind, Artanis/Shield Overload, Varian/Heroic Strike

**One-offs**

* Samuro: Trait has been removed
	* This results in his trait-based talents pointing to the wrong things in abilityId/abilityLinks
* Morales: Healing Beam cooldown has been removed
* Gazlowe & Rexxar: D hotkey is still removed when they have activateable traits
* Rehgar: Grounded Totem has a trailing space in the description
* Tassadar & Varian: now have multiple, comma-separated `role`s
	* Probably fine as-is, but may break some code that was only expecting a single value

I was actually scared to look at TLV, but both them and Chen look great!

**Comment by MGatner** [comment]
All good things. I'll work on the traits and one-offs first.

I noticed the `subunit` change and was undecided. What do you think? We already differentiate primary and sub abilities by the category (e.g. `Greymane` and `GreymaneWorgenForm`) so leaving ability types allows for specifying "subunit: heroic", "subunit: trait", etc. But then again if developers are collapsing these it could get messy putting them all together.

**Comment by stuaroo** [comment]
Eh, I was rather hesitant to bring it up because I'm also undecided!  I can see use cases both ways like you say.  My gut reaction is to change them to basic, trait, etc.  We can always revisit it based on feedback too.

**Comment by MGatner** [comment]
I went ahead and did these by hand so we can get this out there. Some of it will need to be dealt with on next patch, but this buys us some time. I also see that koliva has some updates to HDP to address a few of the issues I put in:
* https://github.com/HeroesToolChest/HeroesDataParser/commits/develop

So that's encouraging and should be coming soon. @stuaroo If you see anything else, as long as it isn't major I think change it by hand for now and then do the merge. Next step will be the repo prune, and then we should be in good shape as far as a baseline for the next patch. Looking forward to easier diffs. ;)

**Pull request merged**
