### PR TITLE
PR

### PR DESCRIPTION
**Pull request by KjellConnelly**
Hey just finished up some basic functionality so NodeJS users can install directly from github. You can add to npm too if you want (since you're the author, I won't do this for you obviously). Added a class with a static function for loading all heroes JSON files into memory and returning a reference. Obviously, there is a lot more that I could add, but I don't have a ton of time right now and wanted some basic functionality for NodeJS users.

### CODE REVIEW

**Comment by MGatner** [comment]
Looks good! I made a few comments in the review. We’ll also need @stuaroo to look over it, and decide on owning the NPM instance.

**Comment by stuaroo** [comment]
Looks good to me too!  @MGatner you've been doing the heavy lifting on this repo over the last year+, so if you'd like to be the owner on npm that would make a lot of sense to me.  I'll leave that up to you!

**Comment by MGatner** [comment]
No way! Nice try though :P 

I don't have a lot of NPM experience but if you want me to look into setting it up I'm glad to. Either way I vote for "Heroes Patch Notes" or stuaroo as the owner/initiator.

**Comment by stuaroo** [comment]
Boo, well alright then.  My only experience with node was some basic/intro stuff a few years ago, so I'll also need to do some research on what to do to register a package on npm.

**Pull request merged**
