### PR TITLE
Implement HDP 3 changes

### PR DESCRIPTION
**Pull request by MGatner**
* Talents' AbilityLinks are now additionally an array
* Included "type" field for talents
* Shortnames now come from game data instead of being derived (changes cho->chogall, thelostvikings->lostvikings)

### CODE REVIEW

**Comment by MGatner** [comment]
@stuaroo Take a look at these - I think everything was discussed already but I'd love to get this merged before Imperius lands on Tuesday.

**Comment by stuaroo** [comment]
@MGatner Couple of odd changes:

* Some talents were changed from an abilityId of Passive to D1 but the type was correctly retained as Passive (ex: Alarak/Mocking Strikes, Ana/Detachable Box Magazine, etc.)
* Talents of type Active and Passive have no abilityLinks (ex: Abathur/Calldown: MULE, Alexstrasza/Exuberance); wanted to confirm that this was expected.
* Noticed Abathur hat talents all had the single abilityId changed to Q1, but Type is still pointing to the correct ability (ex: Pressurized Glands is W type but abilityId is Q1); would it be possible to have abilityId match the Type in those cases?  No big deal if not, just happened to notice that Type was still pulling the old values.
* Alarak/Rite of Rak'Shir changed from Alarak|D1 to Alarak|Trait
* Alarak/Counter-Strike lvl 20 was changed from Alarak|R2 to Alarak|Heroic and has no abilityLinks

Still reviewing but those are some of the main things I noticed so far.  Oh, and PTR's generally start on Mondays, so I'd expect that patch tomorrow.

**Comment by MGatner** [comment]
Good stuff! One-by-one:

* **change from Passive to D1** - Ability links are now separate from Types; koliva is actually pulling them directly from the game files so I don't have to guess on them anymore. If any get too weird we can do a manual override, but expect some type/link spread since the latter is no longer derived from the former

* **Active and Passive have no abilityLinks** - Yes, expected. Abilities are only base kit (plus ult) so talents that stand as their own abilities (like Varian Banner, Garrosh Body Check) won't ever be linked. Some passive talents should have links (e.g. ZaryaDefensiveShielding)

* **Abathur hat talents** - When there are multiple ability links I match the first one for setting the abilityId. Seems like maybe it would make sense to return them in a prioritized order though, which would fix this as well. I'll look into that

* **Alarak/Rite of Rak'Shir** - Coming through as Trait from HDP, with isActive:true. Isn't this a 1 hotkey ability? I'll ask koliva on that one

* **Alarak/Counter-Strike** - Also a koliva question. I'll wait until you've finished reviewing so I can send them all over at once.

**Comment by stuaroo** [comment]
I re-reviewed the items I'd marked down as issues from Passive to D1, and some of the changes are legitimate trait talents.  The vast majority seem to not be Trait related and generally deal with things like auto attack adjustments (e.g. Sonya/War Paint, Nova/One in the Chamber) and spell power increases (Gul'dan/Hunger for Power, Li-Ming/Glass Cannon). Li-Ming is a good example here as her trait is ability resets on kill and none of these D1 talents have anything to do with that. Sorry for the long list:

* Diablo: Malevolence, Diabolical Momentum 
* ETC: Echo Pedal, Hammer-on, Death Metal
* Gul'dan: Hunger for Power, Dark Bargain
* Hanzo: Redemption, Ignore All Distractions
* Johanna: Reinforce
* Kel'Thuzad: Phylactery of Kel'Thuzad, Chilling Touch
* Leoric: Spectral Leech
* Li-Ming: Astral Presence, Power Hungry, Canoneer, Glass Cannon, Tal Rasha's Elements
* Muradin: Give 'em the Axe, Skullcracker
* Murky: Fish Tank
* Nova: One in the Chamber, Anti-Armor Shells
* Raynor: Ace in the Hole, Exterminator, Execute
* Sonya: War Paint
* Tyrande: Elune's Chosen, Darnassian Archery, Shooting Star, Iceblade Arrows
* Varian: High King's Quest
* Zeratul: Master Warp-Blade 

Here are a few more talents that had abilityIds changed from HeroName|D1 to HeroName|Trait; to be clear, these looked like outliers since we haven't previously used HeroName|Trait.  I think it'd be fine if we eventually want to go in that direction but would like to keep usage consistent.  Anyway, the list: 

* Brightwing: Critical Mist
* Cassia: Surge of Light
* Deckard: Safety in Numbers
* D.Va: GG, WP; Nanoweave Suit; Suppressing Fire
* Kharazim: Level 1 talents
* TLV: The Sequel
* Orphea: Invasive Miasma
* Uther: Guardian of Ancient Kings, Redemption, Divine Protection

Several abilityIds are missing their trailing 1 and only have a hotkey (ex: just D.Va|W):

* D.Va: Concussive Pulse
* TLV: Spin to Win, Norse Force, Jump, Nordic Attack Squad
* Mephisto: Ghastly Armor, Frost Storm, Trickery
* Tracer: Jumper, Bullet Time, Spatial Echo

And a few more things that don't fall under any of the above headings:

* Two heroes had a new ability added under a "0" key: Jaina/Improved Ice Block and Kel'Thuzad/Glacial Spike
* Two heroes had _stormhero|Z1 listed in abilityLinks and Id: Malthael/On a Pale Horse and Yrel/Divine Steed

Finally a few abilityLink specific questions, probably will have to ask koliva directly on these (and I know there are more but these I thought of while looking up other issues):

* Nazeebo/Thing of the Deep: shouldn't this have abilityLinks?
* Orphea/Lurking Terror: shouldn't this also have W in abilityLinks?
* Valla/Punishment: shouldn't this also have Trait abilitylinks?

**Comment by MGatner** [comment]
Wow thanks for that comprehensive list! I spot confirmed that these are what’s coming through in raw, e.g.:
  "abilityTalentLinkIds": [
            "WizardTraitCriticalMass"
   ]

I’ll ping koliva on it.

**Comment by MGatner** [comment]
koliva got back that this is intended - you can read the whole thing but basically it seems like passive talents always show trait in game. I’m open with how to deal with this - if you’d rather passive shows abilityId as “hero|Passive” I could do that and still pass the trait in abilityIdLinkId

**Comment by stuaroo** [comment]
Ok, I'm of two minds about this one: it does make sense to link those to trait when they show there in game, but if everything links to trait then what's the use of links?  Then again, I guess you could tell which are actual trait talents by using the new Type, so maybe that's still fine?  Currently I'm leaning towards matching the HeroesDataParser output.

**Comment by MGatner** [comment]
I think the move for Passive talents is to leave the ability links in the array but set abilityId  to "hero|Passive". For example on Ming this would leave Dominance as type:Trait with abilityId and Links "Li-Ming|D1", but Power Hungry would now be type:Passive with abilityId "Li-Ming|Passive" and Links "Li-Ming|D1". Might be slightly confusing but it keeps the game data consistent for anyone using the Links array.

**Comment by MGatner** [comment]
I'm retracting this pull request to reset the forked master so it's ready for today's patch.

**Pull request closed without merging**
