### PR TITLE
Sample rebuild from HeroesDataParser game data

### PR DESCRIPTION
**Pull request by MGatner**
This is just something to look at for a reference point as to what the automated process will spit out. There are some small formatting differences here and there. Main things to pay attention to:
* Orphea
* Extra/missing spaces in some abilities
* Individual hero abilities aligned a bit different: Chen, Kharazim, Alexstrasza, TLV
* All subAbilities and HeroUnit abilities are now type "subunit"
* A number of talents changed their associated ability (e.g. Garrosh|Passive => Garrosh|W1)
* Mounts seem to be considered hotkey Z whether they are activatable or not (Bug? Leave?)

Take a look at the files and let me know if you'd like anything changed. I could also send changes over in parts.

### CODE REVIEW

**Comment by stuaroo** [comment]
So the first thing I was wondering: are you planning to add your compare and update code to the repo in the future?  I'm all for it if you'd like to, and that way anyone could run an update with HeroesDataParser output.  I'm also for including the most recent (or even a history of) HeroesDataParser output in the repo if that would be helpful.

As for the rebuild data, here's a few of the things I noticed: 

* Orphea's heroics and trait talents appear to be missing abilityId's
* For spacing I had been converting all 3 spaces to 2 spaces (basically just because 3 spaces looked 'off' in the string output), which I imagine is why we are now seeing spacing issues.  I think I may have seen some 2 spaces where it was 1 space too, but I'll take a closer look at those on my next pass through.
* Chen/Storm, Earth, and Fire is good, I'd been meaning to add those at some point myself
* Kharazim change looks fine to me; may want to change the abilityId's on level 1 to all be D1 (since they no longer match to an ability)
* For Alexstrasza/Cleansing Flame do we want that to repeat as a subunit heroic under Dragonqueen?  I'm thinking we probably don't need to duplicate it
* TLV I've never known how to handle (since technically they have no base abilities and everything is granted through talents); I think it looks good and we can always adjust in the future if we have a change of heart
* AbilityId changes I think will be fine too.  I knew there were some differences between what I had and what was in game, but I hadn't bothered going through and fixing them all yet.  
    * A random interesting bit: over time the designers changed their philosophy on labeling the dual key talents (i.e. hit an enemy with W, affects next E, etc.).  The old way would almost always label with the dependent key, while nowadays they use the key that benefits assuming the dependent action lands.  I personally preferred the old labeling method (from the example before, if you can't hit your W you'll never get the E benefit, so that's a W talent) but that's not how it is in-game anymore, alas.
* On non-activatable mounts, I'd say that's probably a bug. I originally assumed all mounts would be Z but if you can't activate it then it doesn't have a hotkey.
* Couple other things:
    * With the switch to integer mana costs, a few of the channeled abilities (Arthas/Frozen Tempest, Chromie/Slowing Sands) now show a flat value rather than a mana per second cost.  This one's tough, don't know if we want to special case the few of these that exist or just drop 'em out for simplicity
    * One thing on hotkeys: I think you might want to add numeric hotkeys as strings.  I can anticipate some potential usage issues if we have a data type change for the same key between objects.

**Comment by MGatner** [comment]
> are you planning to add your compare and update code to the repo in the future?
I'm glad to! I'm already posting it to a private repo to transfer from local extraction to our server; I will add it here and make a note in the README.

> Orphea's heroics and trait talents appear to be missing abilityId's
Fixing.

> all 3 spaces to 2 spaces
I'll replace "   " with "  "; let me know if you want any other mods when you look again

> Kharazim change looks fine to me; may want to change the abilityId's on level 1 to all be D1
Fixing.

> Alexstrasza/Cleansing Flame... repeat as a subunit heroic
This came up before and I'd removed it, but on closer inspection this time they are different! The subunit ability launches immediately (which I knew, but didn't know the description was different) and has 10s less cooldown (which I didn't know). I'm in favor of keeping

> TLV
Yeah they are tricky. Right now is as close to the game data, so has the least "intervention" - glad ot tweak it however but this will make future updates easiest.

> A random interesting bit
I'd noticed a lot of those! Didn't know that was why

> non-activatable mounts
I didn't see a way to differentiate between activatable mounts and regular mounts in the gamedata but I will take a closer look. I agree non-activatably should not have hotkey


> Arthas/Frozen Tempest, Chromie/Slowing Sands
I'll look at those.

> add numeric hotkeys as strings
Fixing.

**Comment by MGatner** [comment]
Alright @stuaroo check out https://github.com/heroespatchnotes/heroes-talents/pull/24/commits/d336bea46e340ca00b5b48a8f79ff6c7b1d171eb

**Comment by stuaroo** [comment]
I see the Orphea fix, but now a bunch of abilityId's are missing from level 10 and 20 heroic talents on a majority of heroes.

Kharazim I wasn't very clear on, sorry, I meant his level 1 talents have abilityId's of Kharazim|D1, D2 and D3 and should be updated to all be Kharazim|D1.

That Alexstrasza one is kooky (the cooldown part) and I plan on testing that in-game.  Those are definitely significant enough differences for keeping it in I'd say.

Not sure if the numeric hotkey fix is still in the works but I still see it on a few heroes (examples: Xul, Zeratul)

**Comment by MGatner** [comment]
Latest commits resolve activable/non mounts by checking cooldown, revamped ability mapping for talents (now showing 0 talents missing ability field), and all hotkeys are now strings.
Look this over, both the format and the data. This is likely be a replica of what will come through the automated process after Tuesday's patch.

**Comment by MGatner** [comment]
Arthas/Frozen Tempest and Chromie/Slowing Sands mana cost per second... What about leaving it a flat integer and adding a field, similar to how trait abilities get the ("trait": true) field?

**Comment by stuaroo** [comment]
I really like the idea of adding a field to indicate mana cost per second.  I'm struggling to think of a good name for it though, since "channeled" is probably a bit too broad (and generally makes me think of abilities that can be interrupted and have a flat mana cost like Nazeebo/Ravenous Spirit, Gul'dan/Rain of Destruction, etc.)

**Comment by stuaroo** [comment]
Noticed a couple more issues around abilityIds but overall they are looking pretty solid:

* Fenix talents for Phase Bomb/Repeater Cannon are all being set as Active under abilityId; looking at HeroesDataParser output they are all set to Active there as well, so I may have to open up an issue to get this looked into
* Lucio abilityId's are a mix of Lúcio and Lucio; similarly the Butcher is a mix of The Butcher and Butcher.  I'm thinking these should probably all be Lúcio and The Butcher respectively (to match up with the hero name)

**Pull request merged**
