### PR TITLE
Automated upload of generated data. (2.44.0.73016)

### PR DESCRIPTION
**Pull request by MGatner**

### CODE REVIEW

**Comment by MGatner** [comment]
There are a LOT of changes in this one, some from the game data but a bunch from the latest version of HeroesDataParser. Let me know if you notice anything off - I have a couple new fields to include at some point as well.

**Comment by koliva8245** [comment]
You got the wrong version of HDP, looks like your using the develop-v4 branch.

**Comment by MGatner** [comment]
So I was! I didn't realize there was a new release. I'll run it through again tomorrow - hold off on this merge for now.

**Comment by MGatner** [comment]
Starting this over with HDP 3.3.0

**Pull request closed without merging**
