### PR TITLE
HDP 4 and Patch 2.47.0.75589

### PR DESCRIPTION
**Pull request by MGatner**
@stuaroo This is the first pass at the new HDP format. There's a lot that is different and it didn't all come through nicely but I've changed what I could and will work on some more updates. I wanted to send this PR over in case it was worth it to you for Qhira, and so others would know this fork exists even if the data are quite changed. Glad for any help or feedback.

### CODE REVIEW

**Comment by stuaroo** [comment]
Thanks!  Looking through the differences briefly, it appears that a lot of alternate button states were added (lots of cancel abilities, like `Mosh Pit Cancel`, `Cancel Eye of Horus`, `Cancel Drain Life`).  While it's interesting to see what those are/say, I'm not sure how useful they'd be for the repo's purposes.  What's your opinion on tossing vs. keeping them?

I'll take a closer look at the raw output tomorrow to see if I can notice any patterns on the new additions.  Thanks for the PR/tag too; I'm curious to at least look at Qhira's kit since I didn't get a chance to do anything on the PTR!

**Comment by MGatner** [comment]
When this repo started HDP wasn't a thing (or at least wasn't in use) and for a while we grew together. I think koliva is working on adding more and more to HDP, which is great but also maybe not applicable to this repo which tries for a) consistency and b) conciseness. 

I think it is time on my end to differentiate between what is parsed and what is passed on, maybe keeping my own "ignore" flags. The raw HDP output will always be there (and there's a lot more of it now with version 4!) for those who want it but we can focus the JSON files on what's essential.

IMO hold off on this merge until I have another pass at the data. I'll try for a Qhira "hotfix" in the meantime.

**Comment by stuaroo** [comment]
I finally had a chance to dive deeper into the raw JSON, and it appears that a lot of the differences are originating from `subAbilities`.  Most units now have `subAbilities` where it was more the exception before (in 2.45.0, 11 units had `subAbilities` while 2.47.0 has 94 units with them!).

Maybe you've already thought of this, but rather than a big list of 'ignore' flags you could track which units you actually need `subAbilities` for and otherwise discard `subAbilities` by default?  Just a thought, since the number of added abilities is rather daunting.  I'll keep looking for any other new trends, let me know if I can help with anything else.

**Comment by MGatner** [comment]
Forgot to respond to this comment, but yes I like that approach and I think that the future of my parse-format-export will actually start from heroes-talents and pull in whatever it needs, rather than just loading everything from HDP since it seems to be trending towards a LOT more data.

**Pull request closed without merging**
